{
	"data": "ENC[AES256_GCM,data:GKLwVmr+DHThu1q21b/yEvh3QV+rv3iup93ESBsYBd04ZZsLLQifT/jnVcxwxzuoWgTNTWj/aFRyx6/uX6zgEd24HcLn/07tisLYCMZBF3ojbJr2tAtrqh8NhHT2TtY9fdZYfYPJLTIfyqd+LrOV0EwYX9yPSngctRC8nRf0EPsj54F/TtplBKdMlWcXg7mD/JE7u7S1O+mSzp4e+CWr3ZTn5l/Km6twiRBV6SmWvO6ZSJrT7yKXIvwNmwJvmzQ9Sl65I4vVLYa0GNBwassin9DTYZZn9ae7LR4DN+uSpIFHTOr+BeP/7NArp3ZmPbSdNvvL2V+L0a/gRGxti3EoqrNb1Ery3EGCGbdKtM/8hYk1wmIQ,iv:OdzJ8IlCSRNydIpeautJb3jy6NmkYinGCG5kJlyosDs=,tag:9ehLRD0p7/9GeM5V+UvfyQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1ey9zkargeqmr9ka65kh8pqjzvedy3mld74knhxusxzmun4px7aeqva9a9g",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTDNhakp1YUcvak5tTGgy\nK3dmVWFnN2lQeVlUVENwaHVLYUJ5c0Y3cmpRCkRFTWNDSGFwMVNtaURKUFBXVDNw\nczFYRDMyRkxzdFJkNythN1U2cWFSeWsKLS0tIENiaUdUWU5vL2JxdEdRTG9KWldQ\nemRocWMybFRwMS9jZjRQYWdEeDd0ajgKc10R4CTzDMU/vdpIdsH3N4FJYho5QpWr\nofTnxUQVa8dIZtuxrQIndDCma02CBEurY/4x/ou1mjmwL28fjQ1OlA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-04-07T19:06:43Z",
		"mac": "ENC[AES256_GCM,data:GAm1CHSPHgW9TPza5xohsEi3GcVlUL+S1CN3t6zwDT2/CbfDRXSvdvXnGVQCCxUS5HQavVO3/AuF/ItdvwqVFI2/3jY/GMGaFc9h26PQ/08Up+4Ybk9wRQTzK88+Nkh3ZV9Ov2a55mgdvenJpBXQv/jHw48ceLOgC6UIap9Wt+Y=,iv:LIzTc4YKyQc67K+DSMTOzx/7g1HKDZhRiKnarILhTNY=,tag:LjBqWkvEMSqrwevChPBqNQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}